# NUMPY

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np
print(np.__version__)


1.16.4


# creating arrays:

## 1. Conversion from other Python structures (e.g., lists, tuples)

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
int32


## Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

### Zeros: 

In [16]:
zeros = np.zeros((2,4))

In [17]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 4)

#### arange()

In [22]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### linspace()

In [25]:
lspace = np.linspace(1,20,11)

In [26]:
lspace

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

#### empty()

In [29]:
ep = np.empty((4,6))

In [30]:
ep

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.95820216e-306, 4.45058910e-308, 1.78020169e-306],
       [1.11261162e-306, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 1.33511562e-306],
       [1.11260416e-306, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 2.22522596e-306, 2.10077583e-312]])

In [33]:
ep_like = np.empty_like(lspace)

In [34]:
ep_like

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

#### identity()

In [37]:
iden = np.identity(10)

In [38]:
iden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
iden.shape

(10, 10)

# Dimensional Array

### 0-D Array

In [4]:
import numpy as np
arr = np.array(43)
print(arr)

43


### 1-D Array

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### 2-D Array

In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## Finding the Data Type of each Item

In [7]:
import numpy as np  
a = np.array([[1,2,3]])  
print("Each item is of the type",a.dtype)

Each item is of the type int32


## Ndaaray.shape

In [8]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


## Resize the Ndarray

In [9]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


## ReShape

In [10]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print("printing the original array..")
print(a)
a=a.reshape(2,3)
print("printing the reshaped array..")
print(a)

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


#### ravel()

In [40]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

## Slicing in the Array

In [11]:
import numpy as np  
a = np.array([[1,2],[3,4],[5,6]])  
print(a[0,1])  
print(a[2,1])

2
6


# Numpy AXIS

In [43]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [44]:
arr = np.array(x)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.sum(axis=0)

array([12, 15, 18])

In [47]:
arr.sum(axis=1)

array([ 6, 15, 24])

#### Change rows into Column use 'T'

In [48]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
arr.flat

In [50]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [51]:
arr.ndim

2

In [52]:
arr.size

9

In [54]:
arr.nbytes

36

### Numpy_arg(max,min,sort)

In [55]:
one = np.array([2,4,1,6,7])

In [56]:
one.argmax()

4

In [57]:
one.argmin()

2

In [58]:
one.argsort()

array([2, 0, 1, 3, 4], dtype=int64)

In [68]:
y = [[4,9,7],[1,5,6],[3,8,2]]

In [69]:
ar = np.array(y)

In [76]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [70]:
ar.argmin()

3

In [71]:
ar.argmax()

1

In [72]:
ar.argmin(axis=0)

array([1, 1, 2], dtype=int64)

In [73]:
ar.argmax(axis=0)

array([0, 0, 0], dtype=int64)

In [74]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [75]:
ar.argmax(axis=1)

array([1, 2, 1], dtype=int64)

In [78]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [77]:
ar.argsort()

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [79]:
ar.argsort(axis=0)

array([[1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]], dtype=int64)

In [80]:
ar.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

## Matrix Operations

In [81]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [85]:
ar1 = np.array([[4, 2, 1],
       [1, 5, 2],
       [3, 1, 2]])

In [86]:
ar1

array([[4, 2, 1],
       [1, 5, 2],
       [3, 1, 2]])

In [87]:
ar + ar1

array([[ 8, 11,  8],
       [ 2, 10,  8],
       [ 6,  9,  4]])

In [88]:
ar * ar1

array([[16, 18,  7],
       [ 1, 25, 12],
       [ 9,  8,  4]])

In [89]:
ar - ar1

array([[0, 7, 6],
       [0, 0, 4],
       [0, 7, 0]])

In [90]:
np.sqrt(ar1)

array([[2.        , 1.41421356, 1.        ],
       [1.        , 2.23606798, 1.41421356],
       [1.73205081, 1.        , 1.41421356]])

### Sum(), Max(), Min()

In [95]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [92]:
ar.sum()

45

In [93]:
ar.max()

9

In [94]:
ar.min()

1

#### Where()

In [102]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [115]:
z= ar.reshape((9,))

In [116]:
z

array([4, 9, 7, 1, 5, 6, 3, 8, 2])

In [123]:
np.where(z==5)

(array([4], dtype=int64),)

In [125]:
np.where(z>5)

(array([1, 2, 5, 7], dtype=int64),)

In [127]:
x = np.where(z%2 == 0)
print(x)

(array([0, 5, 7, 8], dtype=int64),)


In [130]:
np.sort(z)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
x = np.searchsorted(z, 7)
print(x)

7


In [131]:
arr = np.array([3, 2, 0, 1])
'''print(-np.sort(-arr))'''
print(np.sort(arr)[::-1])

[3 2 1 0]


In [134]:
ar

array([[4, 9, 7],
       [1, 5, 6],
       [3, 8, 2]])

In [133]:
np.count_nonzero(ar)

9

In [135]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [136]:
ar[1,2]=0

In [137]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

## Check size difference between simple Python list and Numpy Array

In [138]:
import sys

In [139]:
py_arr = [2,4,1,5]

In [140]:
np_arr = np.array(py_arr)

In [141]:
np_arr

array([2, 4, 1, 5])

In [142]:
sys.getsizeof(1) * len(py_arr)

112

In [144]:
np_arr.itemsize * np_arr.size

16